### ISSUE TITLE
redis应该怎么设置？

### ISSUE THREAD

**Issue by lancer-wang** [akynazh/tg-jav-bot#15]
![](https://image.azurebest.eu.org/file/d7ab3b4b498636e2d239e.png)
ERROR: 无法连接到 redis 服务: 127.0.0.1:6379 : Error 111 connecting to 127.0.0.1:6379. Connection refused.
![](https://image.azurebest.eu.org/file/0707476a1aff5c0732058.png)

**Comment by lancer-wang** [comment]
![](https://image.azurebest.eu.org/file/6d4bafc08fdedfa8e396e.png)

**Comment by akynazh** [comment]
> ![](https://camo.githubusercontent.com/6ba752d5e69a411178b9f34d744d53090a65fa7110aeab12210ab0a3f64bf9cc/68747470733a2f2f696d6167652e617a757265626573742e65752e6f72672f66696c652f3664346261666330386664656466613865333936652e706e67)

本地自行安装并启动 redis 服务，注意端口号和配置文件端口号对应即可

**Comment by lancer-wang** [comment]
> > [![](https://camo.githubusercontent.com/6ba752d5e69a411178b9f34d744d53090a65fa7110aeab12210ab0a3f64bf9cc/68747470733a2f2f696d6167652e617a757265626573742e65752e6f72672f66696c652f3664346261666330386664656466613865333936652e706e67)](javascript:void(0))
> 
> 本地自行安装并启动 redis 服务，注意端口号和配置文件端口号对应即可

docker 不是带了redis吗
我端口号没没错啊

**Comment by lancer-wang** [comment]
![](https://image.azurebest.eu.org/file/2ff62b8e770b2a6215380.png)
改成这样可以了

**Comment by akynazh** [comment]
> ![](https://camo.githubusercontent.com/b6bef87de012ecbc3fc89adba0873f0b27f39a7490391bc5bb691d07b746a9a7/68747470733a2f2f696d6167652e617a757265626573742e65752e6f72672f66696c652f3266663632623865373730623261363231353338302e706e67) 改成这样可以了

是的，如果使用 docker，且 network mode 不是 host，需要用容器名称作为 host 否则无法连接到服务。
