### ISSUE TITLE
没有看到有 “config.yaml” 这个文件。

### ISSUE THREAD

**Issue by ericvlog** [akynazh/tg-jav-bot#16]
还有这个错误是什么

ERROR: Could not find a version that satisfies the requirement Jvav==1.4.1
ERROR: No matching distribution found for Jvav==1.4.1

谢谢

**Comment by akynazh** [comment]
1. config.yaml 自己编辑
2. 依赖未更新，已解决，重新按步骤安装下

**Comment by ericvlog** [comment]
谢谢帮助，晚上试试。

**Comment by akynazh** [comment]
config.yaml 具体自己看 readme

**Comment by ericvlog** [comment]
我已经做了 touch config.yaml 把这个放在我 git clone 的文件夹里，已经安装了但有错误。


> [+] Running 3/3
> ⠿ Network tg-search-bot_default            Created                                                                                                                0.1s
> ⠿ Container tg-search-bot-cache-1          Started                                                                                                                0.6s
> ⠿ Container tg-search-bot-tg_search_bot-1  Started                                                                                                                1.2s

It successful docker-compose up -d but I check log container, the config.yaml location should be at?

FileNotFoundError: [Errno 2] No such file or directory: '/root/.tg_search_bot/config.yaml'
Traceback (most recent call last):
    with open(path_config_file, "r", encoding="utf8") as f:
  File "/app/bot.py", line 34, in <module>
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
  File "/app/config.py", line 10, in __init__
    BOT_CFG = BotConfig(PATH_CONFIG_FILE)
    with open(path_config_file, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.tg_search_bot/config.yaml'
  File "/app/config.py", line 10, in __init__

**Comment by ericvlog** [comment]
[2024-03-10 13:09:22,189] INFO: 连接到机器人: @ericxxbot (ID: 7152nnnnn31)
[2024-03-10 13:09:20,782] INFO: 成功读取并加载配置文件

但在电报输入没反应。

![image](https://github.com/akynazh/tg-search-bot/assets/64370408/cd8d07ad-fe24-43ec-806a-dfb6bed066ec)

**Comment by ericvlog** [comment]
刚刚用 docker compose up -d , 不能没反应，就用 pip install -r requirements.txt && python3 bot.py 但有错误  ==requirement typing-extensions>=4.6.1, but you'll have typing-extensions 4.4.0 which is incompatible.==

之后在用 docker-compose up -d 就可以了，有反应了。

**Comment by akynazh** [comment]
看好文档，python>=3.10
