### ISSUE TITLE
请教一下，bot 只能自己私聊用么，怎么样在群组中使用bot？

### ISSUE THREAD

**Issue by wensley** [akynazh/tg-jav-bot#3]

**Comment by akynazh** [comment]
是的，这个 bot 只服务于私人，如果需在群组中使用，需要自己定制。

**Comment by wensley** [comment]
> 是的，这个 bot 只服务于私人，如果需在群组中使用，需要自己定制。

好的，改动大吗？我不会python /捂脸

**Comment by akynazh** [comment]
如果把收藏功能砍掉的话，改动应该不大

**Comment by wensley** [comment]
> 如果把收藏功能砍掉的话，改动应该不大

我能厚着脸皮要你帮我改一版吗？

**Comment by akynazh** [comment]
不行哦。由于个人空闲时间有限，如需定制代码可以通过邮箱私信商量价格。

---

如果没有其它问题，该 issue 将被关闭。

**Comment by wensley** [comment]
好的，谢谢答复！
