### ISSUE TITLE
你好怎么拉docker镜像？

### ISSUE THREAD

**Issue by Gestepo** [akynazh/tg-jav-bot#4]

**Comment by akynazh** [comment]
> 

```
docker-compose up -d
```

**Comment by Gestepo** [comment]
不好意思，没表达清楚。怎么拉你项目的docker😂🤣

**Comment by Gestepo** [comment]
> > 
> 
> ```
> docker-compose up -d
> ```

不好意思，没表达清楚。怎么拉你项目的docker😂🤣

**Comment by akynazh** [comment]
> > > 
> > 
> > 
> > ```
> > docker-compose up -d
> > ```
> 
> 不好意思，没表达清楚。怎么拉你项目的docker😂🤣

就是上面这条命令，建议先了解一下 docker-compose。。

**Comment by akynazh** [comment]
> > > > 
> > > 
> > > 
> > > ```
> > > docker-compose up -d
> > > ```
> > 
> > 
> > 不好意思，没表达清楚。怎么拉你项目的docker😂🤣
> 
> 就是上面这条命令，建议先了解一下 docker-compose。。

你可能是想从 docker 仓库拉取，但是我没有使用 docker 仓库。
